### ISSUE TITLE
Rework GlobalConfig.h.in

### ISSUE THREAD

**Issue by lygstate** [CppMicroServices/CppMicroServices#126]
US_BUILD_SHARED_LIBS can be added as a compiler option.

US_ENABLE_THREADING_SUPPORT default to ON, and we can disable it by compiler option.
And should not appear in GlobalConfig.in.h.
And it's should only affect Cpp files and not in headers.

US_HAVE_VISIBILITY_ATTRIBUTE can be detect by compiler version.

US_HAVE_CXXABI_H should be always exist beyond Windows system.

```
#define CppMicroServices_MAJOR_VERSION @CppMicroServices_MAJOR_VERSION@
#define CppMicroServices_MINOR_VERSION @CppMicroServices_MINOR_VERSION@
#define CppMicroServices_PATCH_VERSION @CppMicroServices_PATCH_VERSION@
#define CppMicroServices_VERSION @CppMicroServices_VERSION@
#define CppMicroServices_VERSION_STR "@CppMicroServices_VERSION@"

These could be able to export as a function. at expose it at the runtime.
Beyond that, Windows also need to include these in it's .rc files.
```
# cmakedefine US_BIG_ENDIAN
# cmakedefine US_LITTLE_ENDIAN

Should be detected at the runtime. Or, if we are cross-compiling, things gonna be wrong.

US_HAVE_REGEX are used for test. We could use the newest version of C++ compiler to do test.
And remove it from GlobalConfig.in.h

**Comment by saschazelzer** [comment]
Thank you for your suggestions. I am curious, what is your motivation to suggest these changes?

Some of the defines you mention are useful for client code (e.g. `US_BUILD_SHARED_LIBS` and the version macros) during compile time, so I'd want to make those available. Not having them in a generated header means that clients either need to remember adding them manually or we rely on the CMake files, which ties clients to it even more. Or did I miss something?

I agree with the `US_ENABLE_THREADING_SUPPORT` comment.

For `US_HAVE_VISIBILITY_ATTRIBUTE` and `US_HAVE_CXXABI_H`, I prefer to rely on feature tests instead of hard coding compiler versions. The latter one is used only internally and we can move it out of GlobalConfig.h.in.

The version macros are useful to conditionally compile client code depending on the version number. Making them functions would prevent this.

The `US_BIG_ENDIAN` (and little variant) macros are determined using compile tests. So this should be correct already in a cross-compilation setup.

I agree, `US_HAVE_REGEX` should be removed from the header file.

**Comment by lygstate** [comment]
My intention is to using CppMicroServices without build it.
Only need to dll at the runtime.

**Comment by saschazelzer** [comment]
For sure, *someone* needs to build CppMicroServices and then the header files together with the binary artifacts can be distributed (via `make install`) for that particular system.

While it would be nice to have all non-generated headers, I think it ultimately does not make much of a difference, especially if we implement a couple of your suggestions.

**Comment by saschazelzer** [comment]
Given the discussion above, I think we should try and move parts of `GlobalConfig.h.in` to an internal common header files that is included from `.cpp` files only. The goal is to expose only the bare minimum in the `GlobalConfig.h` file, which is included in the public `.h` files.

**Comment by achristoforides** [comment]
The work for this seems to have been completed.
