### ISSUE TITLE
Crash when trying to acquire bundle context

### ISSUE THREAD

**Issue by cewee** [CppMicroServices/CppMicroServices#172]
when executing the snippet from the documentation (uServices-bundlecontext) the executable crashes,
because the private ContextBundle part is NULL in GetBundleContext() . This happens on the developement branch.

**Comment by karthikreddy09** [comment]
I think the code in this snippet is based on v2.0 and needs to be updated for v3.0

**Comment by saschazelzer** [comment]
I believe the code is up-to-date with v3.0 but snippets were never required to actually run successfully. Originally, they were intended to be minimal compilable snippets of code.

If it does not lead inflate the snippet code, I'd say we should make them self-contained and hence executable. For others, we could probably just create an object file instead of an executable.

**Comment by cewee** [comment]
I looked at the snippet as an example, because we're trying to integrate the dev branch into a project, and i wasn't able to perform obtain a successful GetBundleContext(), so I wondered what we missed.
Do you have a quick idea what could be missing here ?

**Comment by saschazelzer** [comment]
I think there is just a framework instance missing. Look at the FrameworkFactory class to create a framework some where early in main.

On November 25, 2016 8:05:06 PM GMT+01:00, cewee <notifications@github.com> wrote:
>I looked at the snippet as an example, because we're trying to
>integrate the dev branch into a project, and i wasn't able to perform
>obtain a successful GetBundleContext(), so I wondered what we missed.
>Do you have a quick idea what could be missing here ?
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/CppMicroServices/CppMicroServices/issues/172#issuecomment-263011854

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by cewee** [comment]
I added a framework to the main like this, accessing the BundleContext works fine,
directly via the static GetBundleContext() does not.
```
#include "cppmicroservices/BundleInitialization.h"
CPPMICROSERVICES_INITIALIZE_BUNDLE
int main(int /*argc*/, char* /*argv*/[])
{
  FrameworkFactory ff;
  Framework fw = ff.NewFramework();
  fw.Start();

  // this works, output: system_bundle
  std::cout << fw.GetBundleContext().GetBundle(0).GetSymbolicName() << std::endl;

  // this does not work
  // returns a context, but the BundleContextPrivate object in the PIMPL is null
  auto context = GetBundleContext();
  auto bundle = context.GetBundle();
  std::cout << "Bundle name: " << bundle.GetSymbolicName() << " [id: " << bundle.GetBundleId() << "]\n";
  return 0;
}
```

Your help and hints are greatly appreciated!!

**Comment by saschazelzer** [comment]
Basically, your executable is missing a `manifest.json` resource file. Using `GetBundleContext()` retrieves a context associated with the calling site`s bundle, but your executable does not provide a valid bundle (see [doc](https://github.com/CppMicroServices/CppMicroServices/blob/development/framework/doc/doxygen/MicroServices_TheBundleContext.md))

In v3.0 (yet to be released), bundles are required to provide a manifest. Your case is special because an executable acting as a bundle container is treated slightly differently: all its (valid) bundles are installed automatically on framework initialization. If you are using CMake, you can add the missing pieces lke this:

```{.cmake}
set(_target main)
set(_bundle_name main)
set(_srcs main.cpp)
# Generate a custom "bundle init" file (remove any occurence of
# CPPMICROSERVICES_INITIALIZE_BUNDLE from your sources).
usFunctionGenerateBundleInit(_srcs)

# Track dependencies on resource files
usFunctionGetResourceSource(TARGET ${_target} OUT _srcs)
add_executable(${_target} ${_srcs})

# The US_BUNDLE_NAME compile definition is required
set_property(TARGET ${_target} APPEND PROPERTY COMPILE_DEFINITIONS US_BUNDLE_NAME=${_bundle_name})
set_property(TARGET ${_target} PROPERTY US_BUNDLE_NAME ${_bundle_name})

# Add the manifest file as a resource (assumes you have created a manifest.json file
# with e.g. "{ bundle.name : "main" }"
usFunctionEmbedResources(TARGET ${_target} FILES manifest.json)

target_link_libraries(${_target} CppMicroServices)
```

If you are not using CMake, you would basically need to call the `usResourceCompiler` executable manually, to embed the `manifest.json` into the binary.
