### ISSUE TITLE
Default constructed LDAPFilter seg faults when calling LDAPFilter::Match(...)

### ISSUE THREAD

**Issue by jeffdiclemente** [CppMicroServices/CppMicroServices#251]
Example:
```
ServiceReferenceBase sr;
LDAPFilter filter; 
filter.Match(sr); // This will segfault
```

**Comment by saschazelzer** [comment]
The `LDAPFilter` constructor states that a default constructed filter object is invalid and calling any other method then the boolean conversion operator results in undefined behavior. So the semantics are at least correct according to the documentation.

Doing the changes as in the linke PR means that you would not be able to tell if e.g. a `false` return value of the `Match` function is due to the filter not matching the expression or due to the filter being invalid. It is like if dereferecing a null (shared) pointer returns some sort of "default" instance.

In my opinion, we should keep it as is and test LDAPFilter instances for validity if we do not know how they were constructed, or throw an exception in case a method is called on an invalid instance. Either way, client code needs to prepare for one or the other situation.

**Comment by saschazelzer** [comment]
After thinking more about it, I realized that I was trying to hold on to the original semantics, although the `LDAPFilter` class actually is a strange mix of a value and a pointer type. So if we change the meaning of the default constructor to create a valid instance that by definition matches nothing, we don't need to require clients to check the validity or handle exceptions.

We still have the issue mentioned in the second paragraph above, but the pointer analogy was not a good one to begin with.
