### ISSUE TITLE
No compound key API in AnyMap that does not throw.

### ISSUE THREAD

**Issue by karthikreddy09** [CppMicroServices/CppMicroServices#302]
"AtCompoundKey" API throws if a key is not found in AnyMap. when the API is used extensively, exceptions cause performance degradation. There is no alternative API that allows lookup with a compound key but does not throw. Something similar to "find" or "count" in std::map. 

How about adding a new API that does not throw or modifying the current one to return an empty Any object instead of throwing when a key is not found?

**Comment by karthikreddy09** [comment]
A team at mathworks has run into performance problems with using AtCompoundKey. They have to 1400+ exceptions because they are trying to retrieve bundle metadata using compound keys.

**Comment by saschazelzer** [comment]
Improving the API makes sense. We had several requests like this now and a few ideas have been discussed:

1. Provide a function which returns an empty `Any` object if the key is not found
2. Re-design the API given the current experience to make it easier to work with
3. Drop the current API and include a moden JSON library which is used to retrieve bundle properties from the manifest file (we could just return e.g. a `rapidjson::Document` or some other object from a different JSON library).

Note that 3. is also possible today, if the manifest is retrieved via the resource API and used as a JSON input stream in client code to parse and handle it.

**Comment by karthikreddy09** [comment]
I am not sure what the benefits are for option #3. Exposing a third-party class from our API will prohibit us from switching the underlying parser in the future.  

Option#1 would complicate maintenance.

I prefer Option # 2,  
Changing the function signature to return by value lets us return an empty Any object if a match is not found. Most of the time, compound key is used to retrieve a leaf element so returning by value would not degrade performance by much. 

Change
```
Any& AtCompoundKey(const key_type& key);
const Any& AtCompoundKey(const key_type& key) const;
```
 to 
```
Any AtCompoundKey(const key_type& key) const noexcept;
```

By not returning a reference we take away the ability to modify the map. This should be OK since we use AnyMap to represent bundle properties which are read-only for the user anyway.

**Comment by jeffdiclemente** [comment]
I think the fundamental problem is a lack of meaningful usage information. We only know about MathWork's usage of ```AtCompoundKey```. We could make a better informed decision about ```AtCompoundKey``` with more data.
@saschazelzer  Is there anyone else you know who is using ```AtCompoundKey``` and could provide their feedback on the API? That would be helpful.

Since we are working on 4.0, I'm inclined to say that we break the ```AtCompoundKey``` API and re-factor it to return by value and not throw. I talked with Abhinay and our concern is with large maps being returned. Abhinay is going to determine how long it takes to return an arbitrarily large map using ```AtCompoundKey```.

option #1 means that we have to maintain another API until we deprecate it. Assuming this is for 4.0, my vote goes for breaking the API and re-factoring instead of adding a new API.

__In regards to option 3:__
I didn't realize that users could stream the JSON data using the existing Resource APIs into their own JSON parsers. This is pretty neat. Given this capability, it seems unnecessary to expose any third party JSON APIs from CppMicroServices. There is already the Resource Stream API to do this in a loosely coupled way.

**Comment by saschazelzer** [comment]
I don't have any other usage information or feedback unfortunately.

It also looks like I didn't explain the options I had in mind very well. 1. was meant to modify `AtCompoundKey` such that it does not throw and returns an empty Any. 2. in my mind meant designing a completely different API.

Regarding the by-value versus reference issue, could we maybe just remove the non-const `AtCompoundKey` overload and just have `const Any& AtCompoundKey(key) const noexcept`? Then we can always return by const reference, using a static empty Any in case of a non-existing key.

**Ad option 3:**

Currently `Bundle::GetHeaders()` returns a `AnyMap` by value, which I think should be changed to a const reference. Then, although the manifest can be read via the resource API, I was thinking that if we could get rid of `AnyMap` completely and hold the parsed manifest as e.g. a `rapidjson::Document`, we can just hand this out as a `const&`, without clients having to allocate memory for the manifest string data and parse it again.
