### ISSUE TITLE
How to handle license conflict (Apache-2.0) with the applicable licenses? 

### ISSUE THREAD

**Issue by Raghavendrakamatagi-eng** [CppMicroServices/CppMicroServices#419]
Hello Contributors,

CPP-Microservices (3.3.0) comes under Apache-2.0 but we found a license conflict with these LGPL-2.1 files:

[https://github.com/CppMicroServices/CppMicroServices/blob/v3.3.0/third_party/cppmicroservices_elf.h] (LGPL-2.1+)

[https://github.com/CppMicroServices/CppMicroServices/blob/v3.3.0/framework/include/cppmicroservices/SharedData.h] (LGPL-2.1)

[https://github.com/CppMicroServices/CppMicroServices/blob/v3.3.0/third_party/cppmicroservices_mach-o.h] (BSD-4-Clause-UC)

How would you suggest to solve this issue?
Can the files be removed?

Many thanks,

Regards
Raghavendra

**Comment by jeffdiclemente** [comment]
```SharedData.h``` could be removed with a re-factoring.
The data structures in ```cppmicroservices_elf.h``` and ```cppmicroservices_mach-o.h``` are copied from OS provided headers. These two files could be removed by including the correct OS header and a little code re-factoring.

**Comment by saschazelzer** [comment]
I am not a lawyer. But that code has been carefully reviewed regarding license conflicts, using a layman's approach.

Regarding GPL / LGPL and similar license, the following statement can be made (and found):
> In general, use of header files do not create derivative works, although there can be exceptions. There used to be a lot of attention paid to the amount of code (e.g. number of lines) included from a header file, but no one seems to care about that these days, and this is almost never a problem.

Otherwise, how would commercial software be lawful on Linux at all? It needs to include header files from the kernel or other system interfaces to be able to work with structs, constants, enums etc.

**Comment by Raghavendrakamatagi-eng** [comment]
Hello All,

Thanks for your information.

Regards
Raghavendra

**Comment by Raghavendrakamatagi-eng** [comment]
Hello, just to answer saschazelzer:

We are continually finding license conflicts within the Linux kernel, and continuously cleaning them up too. This is a continuous task to make licensing as clear and non-ambiguous as possible. Header files can contain code too, and be considered as legal artifacts on their own, this is the reason why that statement starts with "in general" instead of "all cases".

On this case, it would help to add the comment from jeffdiclemente on the respective source code header, something on the lines of:

"This header is copied from OS-provided headers and can be removed if desired."

Such a comment helps to prove that does not exist GPL dependency, which in Europe could be understood as making this code portion falling under the scope of GPL too.

Many thanks.

**Comment by saschazelzer** [comment]
Hi, thank you for your input. Such a comment is definitely a good idea. I understand that there may be a grey-zone. We are trying to follow established standards and from my interpretation, our usage is legally unproblematic, even in Europe. If you think otherwise, I would definitely appreciate pointers to more detailed sources of yours.

With such a comment in place, would there still be any legal obstacles in your point of view to using the project in an Apache lincense compatible setting? Thanks!

**Comment by Raghavendrakamatagi-eng** [comment]
OK. Then we will document on our side: "The project authors report that the listed header files contain no substantial code that can be considered as affected by the license scope of the GPL terms".

Would you agree with this statement?

Many thanks.

**Comment by Raghavendrakamatagi-eng** [comment]
Hello,

Any update?

Thanks

**Comment by opajonk** [comment]
Hi! Also I am interested in the outcome of this one...

**Comment by jeffdiclemente** [comment]
we will be removing the aforementioned headers in an upcoming release.
