### ISSUE TITLE
Re-organize public header files

### ISSUE THREAD

**Issue by saschazelzer** [CppMicroServices/CppMicroServices#43]
In anticipation of new modules in the source code, the public header files should be re-organized.

 - Core headers will be located under `include/us`
 - Other module headers will be located under `include/<module>`

All header files will be stripped of the "us" prefix and the `us` namespace will not be optional / changeable any more.

Header files also must not depend on configured information.

**Comment by karthikreddy09** [comment]
@jeffdiclemente 
I like this idea ... headers in specific folders avoids conflict with similar named headers in global scope.

Would it make sense to use include/CppMicroServices instead of include/us ? I think it helps with readability in client code. 

<code>#include "CppMicroServices/Bundle.hpp" </code>
vs
<code>#include "us/Bundle.hpp" </code>

**Comment by saschazelzer** [comment]
You are right, it is definitely more expressive, but also a lot more to type. I would like to get opinions from more people about this.

**Comment by lygstate** [comment]
I like #include "us/Bundle.hpp"
