### ISSUE TITLE
Is CTK part of CppMicroServices or is CppMicroServices part of CTK or neither of both?

### ISSUE THREAD

**Issue by al-sabr** [CppMicroServices/CppMicroServices#508]
Hi I would like to know the answer to the question in the title and I would like also that @saschazelzer confirm/infirm if this tutorial is still actual or outdated.

https://commontk.org/index.php/Documentation/CTK_Plugin_Framework:_Setting_up_a_project#Project_Layout

Can I use CTK and CppMicroServices together or they have different purpose?

Thank you

**Comment by saschazelzer** [comment]
Hi, the two are independent projects. They implement similar ideas using slightly different approaches.

You sure can use both together, but it wouldn't make much sense. The CTK tutorial should still be correct since the CTK Plugin Framework hasn't been actively developed for some time. For further CTK related questions, please ask them on the CTK issue tracker or mailing list. Thanks.
