### ISSUE TITLE
CppMicroServices headers should be self sufficient (i.e. standalone)

### ISSUE THREAD

**Issue by jeffdiclemente** [CppMicroServices/CppMicroServices#66]
All headers should include what it needs and not rely on includes from other headers.

One of the main benefits is that is makes refactoring easier.

**Comment by mrlegowatch** [comment]
I started to investigate this, but could not find a specific cause related to the use case that opened this issue. 

That use case is, David reported that at one point during conversion to 3.0, there was a template expansion issue originating from one CppMicroServices header that was resolved by adding another CppMicroServices header, which he did not believe his client code should be including, but now he can't remember the exact issue, or which header. He did say it was in plugin code, not in a plugin's client's code. Because this issue is regarding template expansion, it can't be found using the straightforward trick of #including only one installed header file at a time, twice, in a test source file.

I ran a variant of the chkhdr script found on StackOverflow (http://stackoverflow.com/questions/1892043/self-sufficient-header-files-in-c-c?lq=1) on the installed headers to find out if there were any latent issues, even though it wouldn't directly find the issue related to the use case.

This script found four header files with issues. Two of the header files are usServiceTrackerPrivate.h and usTrackedService_p.h, both which require ServiceTracker to be declared before they can be included. In CppMicroServices, ServiceTracker.h happens to be included first before either of these includes. Because these are both private headers, I don't believe these are related to David's issue. The other two are usServletConfig.h, which is missing a #include <string>, and usShellService.h, which is missing an include guard (if included twice, it produces errors).

A visual inspection of source files deviating from the rule of always including their own header file first (which is another trick that helps find standalone header issues) found usServiceListeners.cpp including usUtils_p.h before its own header, and usServiceRegistry.cpp including system headers before its own header. These should probably be cleaned up to increase the chances of exposing issues if refactoring takes place.

I can clean up what I found so far, but until we can find a way to flush out template expansion issues resulting from missing dependent headers, these minor cleanups won't resolve the use case that opened this issue.
