### ISSUE TITLE
usResourceCompiler3 error with CMake and vcpkg

### ISSUE THREAD

**Issue by al-sabr** [CppMicroServices/CppMicroServices#677]
I am trying to use the framework like mentioned in http://docs.cppmicroservices.org/en/stable/doc/src/build_instructions.html#cmake-based-projects

I am not able to configure the project via the CMake GUI or via command line.

```
find_package(Poco COMPONENTS Foundation Util Xml REQUIRED)
find_package(Qt5 COMPONENTS Core Gui Xml Widgets REQUIRED)

set(CMAKE_CXX_STANDARD_REQUIRED 1)
set(CMAKE_CXX_STANDARD 17)

find_package(CppMicroServices NO_MODULE REQUIRED)
```

![image](https://user-images.githubusercontent.com/26530975/170153914-41b55d90-7551-46c9-be2f-2821702dae0e.png)

![image](https://user-images.githubusercontent.com/26530975/170153992-85a5dd78-65ab-4b52-afbb-d0a265f5650c.png)

I used **vcpkg install cppmicroservices:x64-windows** to install the package and waited until the end with this result:

```
Installing 2/2 cppmicroservices:x64-windows...
Building cppmicroservices[core]:x64-windows...
-- Using cached CppMicroServices-CppMicroservices-v3.6.0.tar.gz.
-- Cleaning sources at G:/vcpkg/buildtrees/cppmicroservices/src/v3.6.0-e25b133cd3.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source G:/vcpkg/downloads/CppMicroServices-CppMicroservices-v3.6.0.tar.gz
-- Applying patch werror.patch
-- Applying patch fix-dependency-gtest.patch
-- Applying patch fix-warning-c4834.patch
-- Using source at G:/vcpkg/buildtrees/cppmicroservices/src/v3.6.0-e25b133cd3.clean
-- Found external ninja('1.10.2').
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Installing: G:/vcpkg/packages/cppmicroservices_x64-windows/share/cppmicroservices/copyright
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: ......\archives\3c\3c9eaeb2c72ebe6a66d2903a00c35a8760e28dce7ee9a5a186ceab29f4d92d58.zip
Elapsed time to handle cppmicroservices:x64-windows: 5.613 min

Total elapsed time: 6.979 min

cppmicroservices provides CMake targets:
    # this is heuristically generated, and may not be correct
    find_package(cmake CONFIG REQUIRED)
    # note: 5 additional targets are not displayed.    target_link_libraries(main PRIVATE mylib usLogService usWebConsole usHttpService)

```

Although the **usResourceCompiler3.exe** was installed it doesn't recognize and gets confused about its location.

The last part show incorrect information about how to use the **find_package(cmake CONFIG REQUIRED)**. The correct initialization is explained here : http://docs.cppmicroservices.org/en/stable/doc/src/build_instructions.html#cmake-based-projects

**Comment by achristoforides** [comment]
Hi @al-sabr . Thank you for reporting this issue.

Due to bandwidth at the moment, looking into this and trying to resolve it is not a priority at this time.

We understand that there are a few users who utilize vcpkg for acquiring and using CppMicroServices but we really do not have any indication of how many users use this (or the library as a whole for that matter) or if this is a widespread issue that we should prioritize fixing.

I know at one point, one of the other contributors tried making our codebase interact better with vcpkg but it's my understanding that none of the core developers/maintainers were the ones who uploaded the code for vcpkg.

Regarding your issue, I'd recommend using CppMicroServices v3.7.2 (if possible) rather than CppMicroServices 3.6.0 and attempting to install the libraries yourself manually. You can accomplish the install by first building CppMicroServices (e.g., (from CppMicroServices top-level git directory)/build `cmake -G "<YOUR_GENERATOR>" -DUS_ENABLE_THREADING_SUPPORT=ON ..`) and then execute the install target (e.g., `cmake --install` I believe). A release was created a few days ago. 

v3.6.0 is over 2 years old at this point and it is possible that some of the issues you are currently facing may have been addressed.

I am going to close this issue but we can potentially revisit this in the future. If you have questions or comments regarding this or would like to help getting our code to work with vcpkg, please reach out in this comment and I or someone else can re-open it and work with you to help resolve the issues you are facing.
