### ISSUE TITLE
"Activator not found" error case is not handled properly.

### ISSUE THREAD

**Issue by karthikreddy09** [CppMicroServices/CppMicroServices#89]
The current code treats "Activator not found in library" error case the same as "Activator not specified by developer" use case. User tripped on this multiple times and it takes time to debug and figure out why the activator was not called. It should be easier for the user to figure out something went wrong.

**Comment by saschazelzer** [comment]
What would you suggest to "fix" this? We would need a way to know that the developer intended to add an activator. What was the reason for the developer thinking it should work when it actually didn't?

**Comment by karthikreddy09** [comment]
_Use case:_ User was porting his code to use v3.0 and he has also changed the library file location. Since it was an incremental build, there were remnants from previous builds (i.e, a dylib built against v2.1). 

[dlopen](https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man3/dyld.3.html) looks in the library search path first before using the fullpath on Mac OS X.  The old dylib happened to be on the DYLD_LIBRARY_PATH and was loaded into the process when the user called InstallBundle with the path to the new dylib. 

It sounds more like an operator error but I thought the framework could do a better job of reporting the error rather than assuming the dylib doesn't have an activator if it cant find the symbol.

One of the options could be adding an "Bundle-Activator" entry in the manifest.json ? If the entry is not present in manifest, user did not intend to add an activator. If the entry is present and the extern "C" symbol is not found, its an error. I know this adds more to the manifest file but this is how OSGi does it so may be it is acceptable ?

**Comment by saschazelzer** [comment]
I agree that it would be good to be able to provide additional checks for such cases.

A manifest header makes sense, but depending on its value (if it is just a boolean specifying the existance of an activator or a string value describing the activator class name and / or extern C functaion name) this needs to be kept in sync with the code.  And I would like to not create a hard dependency on a manifest file so we could still support simple bundles with activators but no manifest.

For really identifying the problem you describe, I think it makes also sense to get the bundle's library location at runtime based on a symbol it contains and compare this with the originally provided install location. Doing this during the start() method of the bundle would allow us to create an error event and not start such a bundle in the first place.

**Comment by karthikreddy09** [comment]
I would like to propose a manifest property `bundle.hasactivator` with a boolean value. 
- If the property value is set to `true`, it indicates to the framework that the bundle has an activator. The framework will call `dlopen` on the bundle during the bundle's activation. If the function is not found in the shared library, the framework will throw a `std::runtime_error` exception (malformed bundle). 
- If the value is set to `false` or if the property is absent, it indicates that the bundle has no activator and hence no `dlopen` is performed when the bundle is started.

With the current implementation, `dlopen` is called when bundle is started, irrespective of whether it has an activator or not. This prohibits implementation of declarative services(DS) as we want to delay the `dlopen` call on the service provider bundle until a service consumer bundle uses a service from the provider bundle (calls `getService`).

I thought about backwards compatible alternative ... If property is set to true or property does not exist, load the bundle. If property is set to false, do not load the bundle. 
- This option however imposes a requirement on bundles wishing to use DS because if they don't set the property to false, the bundle is unnecessarily loaded well before the service objects are instantiated.

Opinions ??

**Comment by saschazelzer** [comment]
To me, this new manifest header is an additional *hint* to the framework that the bundle is supposed to have an activator and hence reduce developer errors as described in the use case above. As such, it wouldn't tell the framework that the bundle has an activator (this is still ultimately stated by linking in the correctly named activator C function in the bundle implementation). It rather says that the bundle is required to have an activator and a lookup failure by the framework should be an hard error (malformed bundle). Hence I propse to call the header `bundle.activator-required` or similar.

A missing `bundle.activator-required` header or a `false` value would behave in the old way in a sense that the framework looks up the activator function using its pre-defined name and calls it if it is found.

Now with respect to `dlopen`, I agree that the current implementation is not ideal, in particular with respect to DS. I think we can change the "activator lookup" mechanism such that when the bundle is started, we parse the export section of the shared library for the expected function symbol. Since this can be done without loading the library, we can then decide whether to load it and activate the contained bundles. For DS, bundles would not have an activator at all and hence their shared lib would not get loaded.

An open question is how to trigger shared library loading then? But I believe this question is independent from the activation topic here.

**Comment by karthikreddy09** [comment]
If the property is an additional hint to the framework, there is no way for a developer to inform the framework that a bundle does not have an activator. Every bundle has to incur the cost of the activator lookup even when the developer knows there is no activator. (This is the case with existing implementation)

### Behavior when the property is absent ...
According to the OSGi spec, the presence of `bundle.activator` results in the framework instantiating the bundle's activator class and calling its methods. If `bundle.activator` is not present, _no attempt_ is made to instantiate an activator.
Similarly, our framework can rely on the property to lookup the activator and absence of the property should mean framework would _not attempt_ the lookup.

### Framework vs Linker :
Changing the activator-lookup to parse export tables requires the framework to have knowledge of  the linker world. It would break our requirement to keep the linker world separate from the Framework world. Moreover, It will add a layer of complexity to the implementation since we have to deal with several file formats.

I understand you want keep it simple for bundle developers to create a bundle. We already require users to provide a manifest file with `bundle.symbolic_name`, one more required property seems reasonable (if they intend to implement an activator). This is more inline with the OSGi spec and it will keep our implementation simple. Manifest file creation can be automated and we have an open task to provide some level of automation.

### Trigger to load library
The trigger for shared library loading could be something analogous to the `Bundle::loadClass` API in Java OSGi. Apache Felix SCR uses `Bundle::loadClass` to load the service implementation class right before instantiating it in response to `getService`.

**Comment by saschazelzer** [comment]
I thought more about this and think you are right. If the bundle provides a manifest file (which is currently required), the `bundle.activator` header should not be a hint but used directly. What do you think about using `bundle.activator` as is for the name? If its value is a boolean, we look for the activator function using our naming convention. I we decide later to also support custom names, a string value type can be used for that, keeping the same header key.

As a side note, I was never happy with requiring users to create a manifest file. For simple bundles, I believe it is desirable to be able to create them by e.g. just compiling a single source file, without the need for invoking any external tool (resource compiler) or create another text file. In my opinion, this lowers the entry barrier for C++ developers and will help the project in the long run gaining more users. Just think about how easy it could be to create a bundle with a single command line call to the compiler.

When you mention the linker, I would rather talk about object formats. In my view, they are well documented and stable, and there is not really much complexity to it. Parsing code for the major three (PE, ELF, MachO) already exists in the repository. Compare that code with the miniz code. The lines of code in miniz is already significantly higher compared to the parsing code for the three object formats together! Let alone the dense coding style. Additionaly, I don't like duplicating information. If we can access bundle specific information by reading the shared library (without significant overhead), we should do so and not require the user to duplicate this information in a separate file which needs to be kept in sync (partially). If someone is ever going to use CppMicroServices with a compiler that produces an unsupported object file format, manifest files as a resource will always be a viable alternative.

**Comment by karthikreddy09** [comment]
Yes, +1 for using the property name as is. I will get started on implementing this if there are no concerns.

I thought about **not having to run an extra tool or create a file** scenario and it is very appealing. I will create a separate document with a proposal. One question though ...
- Is it possible to create an OSGi bundle using plain Java code ? The only annotation support I found in the core spec is related to semantic versioning. 

You are right, we are dealing with object file formats rather than depending on the linkers. Since we look for simple "C" style symbols, the lookup should be straightforward. I agree that we should not require the user to duplicate information.

**Comment by saschazelzer** [comment]
Sounds good, this will be a nice feature.

I thought that you are probably going to experience different startup times with the "linked" zip resources. As you noted, the zip signature search can be expensive. In the worst case, the framework needs to read the whole shared library and will likely find byte sequences which match the signature, triggering the zip init logic. If this fails (because the match was a false positive), the search continues.

If we always require manifest files embedded as a zip resource at the end of the shared library, the current system works well. In the other case, possibly not so much. Note that if we introduce persistent framework storage, subsequent application starts would not install bundles again and hence not have the same overhead.

Being able to jump to the section containing the zip blob would speed up things for sure. If no such section exists, it would also be good to know in advance if we should search for a zip blob or if the bundle does not contain any resources at all and we can just skip the whole process.

**Comment by karthikreddy09** [comment]
Fixed in PR#148
